// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

String readFile({required String path}) =>
    RustLib.instance.api.crateApiSimpleReadFile(path: path);

void saveFile({required String path, required String content}) =>
    RustLib.instance.api.crateApiSimpleSaveFile(path: path, content: content);
